const plugin = require("./dist/index.js");

console.log("🧪 Testing pytorch-dropout-layer Plugin\n");

// Test plugin loading
try {
  console.log("✅ Plugin loaded successfully");
  console.log("📦 Plugin name:", plugin.default.prototype.name);
  console.log("🔧 Plugin type:", plugin.default.prototype.nodeType);
} catch (error) {
  console.error("❌ Failed to load plugin:", error.message);
  process.exit(1);
}

// Test plugin instantiation
let pluginInstance;
try {
  pluginInstance = new plugin.default();
  console.log("✅ Plugin instantiated successfully");
} catch (error) {
  console.error("❌ Failed to instantiate plugin:", error.message);
  process.exit(1);
}

// Test code generation with different dropout settings
const testCases = [
  {}, // Default settings
  { variableName: "my_dropout", p: 0.3 },
  { variableName: "high_dropout", p: 0.8, inplace: false },
  { variableName: "inplace_dropout", p: 0.2, inplace: true },
  { p: 0.1 }, // Low dropout for fine-tuning
  { variableName: "zero_dropout", p: 0.0 }, // No dropout
  { variableName: "max_dropout", p: 1.0 }, // Maximum dropout
];

console.log("\n🔧 Testing dropout layer code generation...\n");

for (let i = 0; i < testCases.length; i++) {
  const testCase = testCases[i];
  console.log(`Test ${i + 1}: ${JSON.stringify(testCase)}`);

  try {
    // Test validation
    pluginInstance.validateSettings(testCase);
    console.log("  ✅ Settings validation passed");

    // Test code generation
    const code = pluginInstance.getTranslationCode(testCase);
    console.log("  ✅ Code generation successful");
    console.log("  📝 Generated code:");
    console.log(`    ${code}`);

    // Test dependencies
    const deps = pluginInstance.getDependencies();
    console.log(
      "  📦 Dependencies:",
      deps.length > 0 ? deps.join(", ") : "none"
    );

    // Test imports
    const imports = pluginInstance.getImports();
    console.log("  📥 Imports:", imports.length, "statements");
  } catch (error) {
    console.error("  ❌ Test failed:", error.message);
    process.exit(1);
  }

  console.log("");
}

// Test validation error cases
console.log("🚨 Testing validation error cases...\n");

const errorTestCases = [
  { p: -0.1 }, // Invalid probability (negative)
  { p: 1.5 }, // Invalid probability (> 1)
  { p: "0.5" }, // Invalid type for probability
  { variableName: 123 }, // Invalid type for variable name
  { inplace: "true" }, // Invalid type for inplace
];

for (let i = 0; i < errorTestCases.length; i++) {
  const testCase = errorTestCases[i];
  console.log(`Error Test ${i + 1}: ${JSON.stringify(testCase)}`);

  try {
    pluginInstance.validateSettings(testCase);
    console.error("  ❌ Expected validation to fail, but it passed");
    process.exit(1);
  } catch (error) {
    console.log("  ✅ Validation correctly failed:", error.message);
  }

  console.log("");
}

console.log(
  "🎉 All tests passed! Your pytorch-dropout-layer plugin is working correctly."
);
console.log("\nGenerated Code Examples:");
console.log(
  "• dropout_layer = dropout(0.5) # Generated by @tensorify/pytorch-dropout-layer"
);
console.log(
  "• my_dropout = dropout(p=0.3) # Generated by @tensorify/pytorch-dropout-layer"
);
console.log(
  "• inplace_dropout = dropout(p=0.2, inplace=True) # Generated by @tensorify/pytorch-dropout-layer"
);
console.log("\nNext steps:");
console.log("1. ✅ Plugin logic implemented");
console.log("2. ✅ Settings interface configured for dropout layer");
console.log("3. ✅ Validation and code generation logic added");
console.log("4. ✅ Built and tested successfully");
console.log("5. 📤 Ready to publish to the Tensorify registry!");
