import {
  INode,
  ModelLayerNode,
  ModelLayerSettings,
  NodeType,
} from "@tensorify.io/sdk";

/**
 * Settings interface for the Dropout Layer
 */
export interface DropoutLayerSettings extends ModelLayerSettings {
  /** Variable name for the layer instance */
  variableName?: string;
  /** Dropout probability (between 0 and 1) */
  p?: number;
  /** Whether to apply inplace operation */
  inplace?: boolean;
}

/**
 * PyTorch Dropout Layer Plugin - A Tensorify plugin that implements dropout regularization
 */
export default class PytorchDropoutLayerPlugin
  extends ModelLayerNode<DropoutLayerSettings>
  implements INode<DropoutLayerSettings>
{
  /** Name of the node */
  public readonly name: string = "pytorch-dropout-layer";

  /** Template used for translation */
  public readonly translationTemplate: string = "pytorch_dropout_layer";

  /** Number of input lines */
  public readonly inputLines: number = 1;

  /** Number of output lines */
  public readonly outputLinesCount: number = 1;

  /** Number of secondary input lines */
  public readonly secondaryInputLinesCount: number = 0;

  /** Node type */
  public readonly nodeType: NodeType = NodeType.MODEL_LAYER;

  /** Default settings */
  public readonly settings: DropoutLayerSettings = {
    variableName: "dropout_layer",
    p: 0.5,
    inplace: false,
  };

  /**
   * Generate PyTorch dropout layer code
   */
  public getTranslationCode(
    settings: DropoutLayerSettings,
    children?: any,
    context?: any
  ): string {
    // Validate settings
    this.validateSettings(settings);

    // Get settings with defaults
    const variableName =
      settings.variableName || this.settings.variableName || "dropout_layer";
    const p = settings.p !== undefined ? settings.p : this.settings.p || 0.5;
    const inplace =
      settings.inplace !== undefined
        ? settings.inplace
        : this.settings.inplace || false;

    // Build parameters array
    const params: string[] = [];

    // Add probability parameter
    if (p !== 0.5) {
      params.push(`p=${p}`);
    }

    // Add inplace parameter if true
    if (inplace) {
      params.push(`inplace=${inplace ? "True" : "False"}`);
    }

    // Generate the dropout code
    const paramsStr = params.length > 0 ? `(${params.join(", ")})` : `(${p})`;
    return `${variableName} = dropout${paramsStr} # Generated by @ari1337an/pytorch-dropout-layer`;
  }

  /**
   * Validate plugin settings
   */
  public validateSettings(settings: DropoutLayerSettings): boolean {
    // Validate dropout probability
    if (settings.p !== undefined) {
      if (typeof settings.p !== "number") {
        throw new Error("Dropout probability 'p' must be a number");
      }
      if (settings.p < 0 || settings.p > 1) {
        throw new Error("Dropout probability 'p' must be between 0 and 1");
      }
    }

    // Validate variable name
    if (
      settings.variableName !== undefined &&
      typeof settings.variableName !== "string"
    ) {
      throw new Error("Variable name must be a string");
    }

    // Validate inplace parameter
    if (
      settings.inplace !== undefined &&
      typeof settings.inplace !== "boolean"
    ) {
      throw new Error("Inplace parameter must be a boolean");
    }

    return true;
  }

  /**
   * Get required dependencies
   */
  public getDependencies(): string[] {
    return ["torch", "torch.nn.functional"];
  }

  /**
   * Get required imports
   */
  public getImports(context?: any): string[] {
    return [
      "import torch",
      "import torch.nn.functional as F",
      "from torch.nn.functional import dropout",
    ];
  }
}
